{
 "title": "Gunicorn overview",
 "tags": [ "gunicorn" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{}, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_labels{namespace=\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(gunicorn_max_worker_threads{}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX HTTP 502/504",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"50[24]\"}[2m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "100\n* sum by(pod) (increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$pod\",container!~\"POD|\"}[1m]))\n/ sum by(pod) (increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$pod\",container!~\"POD|\"}[1m]))",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(gunicorn_pending_connections{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "max(pending_connections)"
    },
    {
     "expr": "min(gunicorn_max_worker_connections{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "max connections per worker"
    },
    {
     "expr": "max(gunicorn_active_worker_connections{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "max(active_connections)"
    }
   ]
  },
  {
   "title": "Pod logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pending requests by worker",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max(gunicorn_pending_requests{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "max(pending_requests)"
    },
    {
     "expr": "min(gunicorn_max_worker_threads{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "max threads per worker"
    }
   ]
  }
 ]
}