{
 "title": "NGINX",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{}, ingress)"
    }
   },
   {
    "name": "pod",
    "label": "Controller pod(s)",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{ingress=~\"$ingress\"}, controller_pod) "
    }
   },
   {
    "name": "path",
    "label": "Path",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\"}, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "% Success (period)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the entire period in the top-right hand corner.\n\nNOTE: Ignoring 4xx in this metric, since a 4xx is a normal response for errant/invalid request.  This helps prevent this percentage from being affected by typical web scanners and security probes.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\", status!~\"5.*\"}[${__range_s}s]\n      )\n   ) by (ingress)\n/ \n\nsum(\n  rate(\n    nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[${__range_s}s]\n      )\n    ) by (ingress)\n    \n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Requests (2m)",
   "type": "stat",
   "description": "The number of HTTP requests made over the last minute",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "% Success (2m)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the last minute.\n\nNOTE: Ignoring 4xx in this metric, since a 4xx is a normal response for errant/invalid request.  This helps prevent this percentage from being affected by typical web scanners and security probes.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\", status!~\"5.*\",}[$__interval])) / \nsum(rate(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (2m)",
   "type": "stat",
   "description": "This is the number of successful requests in the last minute.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\", status=~\"(1|2).*\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 3xx (2m)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\", status=~\"3.*\"}[2m]))  or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 4xx (2m)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\", status=~\"4.*\"}[$__interval]))  or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP 5xx (2m)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\", status=~\"5.*\"}[$__interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "graph",
   "description": "This is the total number of requests processed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[$__interval])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency (Average Percentiles)",
   "type": "timeseries",
   "description": "This graph can help assess and help us meet SLA requirements as far as the responsive time of our services.\n\nFor a more detailed latency graph broken out by ingress please open the closed tab at the bottom because it is very CPU intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        ingress=~\"$ingress\", \n        controller_pod=~\"$pod\", \n        path=~\"$path\"}[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        ingress=~\"$ingress\", \n        controller_pod=~\"$pod\", \n        path=~\"$path\"}[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(\n  0.9,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        ingress=~\"$ingress\", \n        controller_pod=~\"$pod\", \n        path=~\"$path\"}[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        ingress=~\"$ingress\", \n        controller_pod=~\"$pod\", \n        path=~\"$path\"}[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(\n  0.75,\n  sum by (le)(\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        status!=\"404|500|304|499\",\n        ingress=~\"$ingress\", \n        controller_pod=~\"$pod\", \n        path=~\"$path\"}[$__interval]\n    )\n  )\n)",
     "legendFormat": "0.75"
    },
    {
     "expr": "(\n\n(sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\", \n    controller_pod=~\"$pod\",\n    le=\"0.01\", \n    path=~\"$path\"}[$__interval]))\n* 0.01)\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"0.1\", \n    path=~\"$path\"}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"0.01\",\n    path=~\"$path\"}[$__interval])))\n* 0.1)\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"1\", \n    path=~\"$path\"}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"0.1\", \n    path=~\"$path\"}[$__interval])))\n* 1)\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"10\", \n    path=~\"$path\"}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"1\", \n    path=~\"$path\"}[$__interval])))\n* 10 )\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"30\", \n    path=~\"$path\"}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"10\", \n    path=~\"$path\"}[$__interval])))\n* 30 )\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"60\", \n    path=~\"$path\"}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"30\", \n    path=~\"$path\"}[$__interval])))\n* 60 )\n\n+\n\n((sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"+Inf\", \n    path=~\"$path\"}[$__interval]))\n-\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"60\", \n    path=~\"$path\"}[$__interval])))\n* 120 )\n\n) / \n\nsum(increase(nginx_ingress_controller_request_duration_seconds_bucket{\n    status!=\"404|500|304\",\n    ingress=~\"$ingress\",\n    controller_pod=~\"$pod\",\n    le=\"+Inf\", \n    path=~\"$path\"}[$__interval]))\n",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Latency Heatmap",
   "type": "heatmap",
   "description": "This graph can help assess and help us meet SLA requirements as far as the responsive time of our services.\n\nFor a more detailed latency graph broken out by ingress please open the closed tab at the bottom because it is very CPU intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (le)(\n  increase(\n    nginx_ingress_controller_request_duration_seconds_bucket{\n      status!=\"404\", \n      status!=\"500\", \n      ingress=~\"$ingress\", \n      controller_pod=~\"$pod\", \n      path=~\"$path\"\n    }[$__interval]\n  )\n)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "New Connections Opened (Controller / Ingress Pod)",
   "type": "graph",
   "description": "NOTE: This does not work per ingress/namespace\n\nThis is the number of new connections opened by the controller",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_nginx_process_connections{state=~\"active\", controller_pod=~\"$pod\"}[$__interval]))",
     "legendFormat": "New Connections"
    }
   ]
  },
  {
   "title": "Total Connections Open (Controller / Ingress Pod)",
   "type": "graph",
   "description": "NOTE: This does not work per ingress/namespace\n\nThe total number of connections opened to our ingresses.  If you have a CDN in front of our services, it is not unusual for this to be very low.  If/when we use something like websockets with a persistent connection this can/will be very high.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{state=~\"active\", state=~\"active\", controller_pod=~\"$pod\"}[$__range]))",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "CPU Intensive / Optional Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Success Rate (non-5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    nginx_ingress_controller_requests{status!~\"5.*\", ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[2m]\n      )\n   )\n/ \n\nsum(\n  rate(\n    nginx_ingress_controller_requests{ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[2m]\n      )\n    )\n",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status!=\"404\", status!=\"500\", ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status!=\"404\", status!=\"500\", ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{status!=\"404\", status!=\"500\", ingress=~\"$ingress\", controller_pod=~\"$pod\", path=~\"$path\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  }
 ]
}