{
 "title": "PostgreSQL",
 "tags": [
  "AnalyticKit",
  "PostgreSQL"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(pg_up{}, instance)"
    }
   },
   { "name": "database", "label": "Database", "query": { "query": "label_values(datname)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_postmaster_start_time_seconds{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{instance=~\"$instance\"}[$interval])) + \nsum(irate(pg_stat_database_xact_rollback{instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=\"analytickit\"}[5m])",
     "legendFormat": "Commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=\"analytickit\"}[5m])",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Slow queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  rate(pg_slow_queries{instance=\"$instance\"}[$__interval])\n)",
     "legendFormat": "Slow queries"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(pg_stat_activity_count{instance=\"$instance\"}[$__interval])) /\nsum(pg_settings_max_connections{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Cache hit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=\"analytickit\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=\"analytickit\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=\"analytickit\"})"
    }
   ]
  },
  {
   "title": "Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_tup_inserted{instance=\"$instance\"}[$interval]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_fetched{instance=\"$instance\"}[$interval]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_deleted{instance=\"$instance\"}[$interval]))",
     "legendFormat": "Deleted"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_updated{instance=\"$instance\"}[$interval]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(irate(pg_stat_database_tup_returned{instance=\"$instance\"}[$interval]))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (mode) (\n  avg_over_time(pg_locks_count{instance=\"$instance\", datname=\"$database\"}[$__interval])\n)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Conflicts / Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks{instance=\"$instance\"}[$interval]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts{instance=\"$instance\"}[$interval]))",
     "legendFormat": "Conflicts"
    }
   ]
  },
  {
   "title": "Connection (by state)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{instance=\"$instance\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "pg_settings_max_connections{instance=\"$instance\"}",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=\"analytickit\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=\"analytickit\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=\"analytickit\"})",
     "legendFormat": "Hit rate"
    }
   ]
  }
 ]
}