{
 "title": "ZooKeeper",
 "tags": [
  "AnalyticKit",
  "Zookeeper"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "znode_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "znode_count{}", "legendFormat": "{{instance}} znode_count" },
    { "expr": "ephemerals_count{}", "legendFormat": "{{instance}} ephemerals" }
   ]
  },
  {
   "title": "znode_count_rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "rate(znode_count{}[$interval])", "legendFormat": "{{instance}} znode_count_rate" },
    {
     "expr": "rate(ephemerals_count{}[$interval])",
     "legendFormat": "{{instance}} ephemerals_rate"
    }
   ]
  },
  {
   "title": "global_sessions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "global_sessions{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "local_sessions ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "local_sessions{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "write_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "write_per_namespace_sum{}",
     "legendFormat": "{{instance}} write_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "read_per_namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "read_per_namespace_sum{}",
     "legendFormat": "{{instance}} read_per_namespace:{{key}}"
    }
   ]
  },
  {
   "title": "approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "approximate_data_size{}",
     "legendFormat": "{{instance}} approximate_data_size"
    }
   ]
  },
  {
   "title": "packets_received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_received{}", "legendFormat": "{{instance}} packets_received" }
   ]
  },
  {
   "title": "packets_sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "packets_sent{}", "legendFormat": "{{instance}} packets_sent" }
   ]
  },
  {
   "title": "response_packet_cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "response_packet_cache_misses{}",
     "legendFormat": "{{instance}} response_packet_cache_misses"
    },
    {
     "expr": "response_packet_cache_hits{}",
     "legendFormat": "{{instance}} response_packet_cache_hits"
    },
    {
     "expr": "response_packet_get_children_cache_misses{}",
     "legendFormat": "{{instance}} response_packet_get_children_cache_misses"
    },
    {
     "expr": "response_packet_get_children_cache_hits{}",
     "legendFormat": "{{instance}} response_packet_get_children_cache_hits"
    }
   ]
  },
  {
   "title": "unrecoverable_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "unrecoverable_error_count{}",
     "legendFormat": "{{instance}} unrecoverable_error_count"
    }
   ]
  },
  {
   "title": "digest_mismatches_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "digest_mismatches_count{}",
     "legendFormat": "{{instance}} digest_mismatches_count"
    }
   ]
  },
  {
   "title": "startup_snap_load_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_snap_load_time_sum{}",
     "legendFormat": "{{instance}} startup_snap_load_time"
    }
   ]
  },
  {
   "title": "startup_txns_loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "startup_txns_loaded_sum{}",
     "legendFormat": "{{instance}} startup_txns_loaded"
    }
   ]
  },
  {
   "title": "db_init_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "dbinittime_sum{}", "legendFormat": "{{instance}} db_init_time" }
   ]
  },
  { "title": "Quorum/Leader Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "quorum_size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(quorum_size{})", "legendFormat": "quorum_size" }
   ]
  },
  {
   "title": "leader",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "leader_uptime{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "leader_uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "leader_uptime{}", "legendFormat": "{{instance}} leader_uptime" }
   ]
  },
  {
   "title": "learner/observer",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "max(learners{})", "legendFormat": "learners" },
    {
     "expr": "max(synced_non_voting_followers{})",
     "legendFormat": "synced_non_voting_followers"
    },
    { "expr": "max(synced_observers{})", "legendFormat": "synced_observers" }
   ]
  },
  {
   "title": "election_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "election_time_count{}",
     "legendFormat": "{{instance}} election_time_count"
    },
    {
     "expr": "election_time_sum{}",
     "legendFormat": "{{instance}} election_time_sum(ms)"
    },
    {
     "expr": "election_time_sum/election_time_count{}",
     "legendFormat": "{{instance}} election_avg_time(ms)"
    }
   ]
  },
  {
   "title": "quorum uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "uptime{}", "legendFormat": "{{instance}} uptime" }
   ]
  },
  {
   "title": "learner_commit_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "learner_commit_received_count{}",
     "legendFormat": "{{instance}} learner_commit_received_count"
    }
   ]
  },
  {
   "title": "commit_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "commit_count{}", "legendFormat": "{{instance}} commit_count" }
   ]
  },
  {
   "title": "snap_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "snap_count{}", "legendFormat": "{{instance}} snap_count" }
   ]
  },
  {
   "title": "diff_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "diff_count{}", "legendFormat": "{{instance}} diff_count" }
   ]
  },
  {
   "title": "looking_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "looking_count{}", "legendFormat": "{{instance}} looking_count" }
   ]
  },
  {
   "title": "proposal_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "proposal_count{}", "legendFormat": "{{instance}} proposal_count" }
   ]
  },
  {
   "title": "proposal_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "last_proposal_size{}",
     "legendFormat": "{{instance}} last_proposal_size"
    },
    { "expr": "max_proposal_size{}", "legendFormat": "{{instance}} max_proposal_size" },
    { "expr": "min_proposal_size{}", "legendFormat": "{{instance}} min_proposal_size" }
   ]
  },
  {
   "title": "follower_sync_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(follower_sync_time_sum{}[1m])",
     "legendFormat": "{{instance}} follower_sync_time"
    }
   ]
  },
  {
   "title": "learner_handler_qp_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "learner_handler_qp_size_sum{}",
     "legendFormat": "{{instance}} learner_handler_qp_size_sum sid:{{key}}"
    }
   ]
  },
  {
   "title": "quit_leading_due_to_disloyal_voter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quit_leading_due_to_disloyal_voter{}",
     "legendFormat": "{{instance}} quit_leading_due_to_disloyal_voter"
    }
   ]
  },
  {
   "title": "Observer Master",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(om_commit_process_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} om_commit_process_time"
    },
    {
     "expr": "rate(om_proposal_process_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} om_proposal_process_time"
    }
   ]
  },
  { "title": "Session/Watch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "watch_count{}", "legendFormat": "{{instance}} watch_count" }
   ]
  },
  {
   "title": "node_changed_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_changed_watch_count_sum{}",
     "legendFormat": "{{instance}} node_changed_watch_count"
    }
   ]
  },
  {
   "title": "node_children_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_children_watch_count_sum{}",
     "legendFormat": "{{instance}} node_children_watch_count"
    }
   ]
  },
  {
   "title": "node_deleted_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_deleted_watch_count_sum{}",
     "legendFormat": "{{instance}} node_deleted_watch_count"
    }
   ]
  },
  {
   "title": "node_created_watch_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_created_watch_count_sum{}",
     "legendFormat": "{{instance}} node_created_watch_count"
    }
   ]
  },
  {
   "title": "revalidate_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "revalidate_count{}", "legendFormat": "{{instance}} revalidate_count" }
   ]
  },
  {
   "title": "stale_sessions_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "stale_sessions_expired{}",
     "legendFormat": "{{instance}} stale_sessions_expired"
    }
   ]
  },
  {
   "title": "dead_watchers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dead_watchers_cleared{}",
     "legendFormat": "{{instance}} dead_watchers_cleared"
    },
    {
     "expr": "dead_watchers_queued{}",
     "legendFormat": "{{instance}} dead_watchers_queued"
    },
    {
     "expr": "rate(dead_watchers_cleaner_latency_sum{}[$interval])",
     "legendFormat": "{{instance}} dead_watchers_cleaner_latency"
    }
   ]
  },
  {
   "title": "add_dead_watcher_stall_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "add_dead_watcher_stall_time{}",
     "legendFormat": "{{instance}} add_dead_watcher_stall_time"
    }
   ]
  },
  { "title": "Client/Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_requests{}",
     "legendFormat": "{{instance}} outstanding_requests"
    }
   ]
  },
  {
   "title": "client_response_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "last_client_response_size{}",
     "legendFormat": "{{instance}} last_client_response_size"
    },
    {
     "expr": "min_client_response_size{}",
     "legendFormat": "{{instance}} min_client_response_size"
    },
    {
     "expr": "max_client_response_size{}",
     "legendFormat": "{{instance}} max_client_response_size"
    }
   ]
  },
  {
   "title": "bytes_received_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bytes_received_count{}",
     "legendFormat": "{{instance}} bytes_received_count"
    }
   ]
  },
  {
   "title": "connection_request_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_request_count{}",
     "legendFormat": "{{instance}} connection_request_count"
    }
   ]
  },
  {
   "title": "num_alive_connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "num_alive_connections{}",
     "legendFormat": "{{instance}} num_alive_connections"
    }
   ]
  },
  {
   "title": "connection_rejected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_rejected{}",
     "legendFormat": "{{instance}} connection_rejected"
    }
   ]
  },
  {
   "title": "connection_drop_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_drop_count{}",
     "legendFormat": "{{instance}} connection_drop_count"
    }
   ]
  },
  {
   "title": "connection_drop_probability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "connection_drop_probability{}",
     "legendFormat": "{{instance}} connection_drop_probability"
    }
   ]
  },
  {
   "title": "sessionless_connections_expired",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sessionless_connections_expired{}",
     "legendFormat": "{{instance}} sessionless_connections_expired"
    }
   ]
  },
  {
   "title": "connection_token_deficit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 156 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(connection_token_deficit_sum{}[$interval])",
     "legendFormat": "{{instance}} connection_token_deficit"
    }
   ]
  },
  { "title": "Disk/Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 164 } },
  {
   "title": "open_file_descriptor",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "open_file_descriptor_count{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "fsync_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fsynctime_sum * 1000 /fsynctime_count{}",
     "legendFormat": "{{instance}} fsynctime_avg(μs)"
    },
    { "expr": "irate(fsynctime_sum{}[1m])", "legendFormat": "{{instance}} fsynctime_rate" }
   ]
  },
  {
   "title": "snapshot_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(snapshottime_sum{}[$interval])",
     "legendFormat": "{{instance}} snapshot_time_rate"
    }
   ]
  },
  { "title": "Prep_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "prep_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prep_process_time_sum{}[$interval])",
     "legendFormat": "{{instance}} prep_process_time"
    }
   ]
  },
  {
   "title": "prep_processor_queue_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 190 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(prep_processor_queue_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} prep_processor_queue_time_ms"
    }
   ]
  },
  {
   "title": "prep_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prep_processor_queue_size_sum{}[$interval])",
     "legendFormat": "{{instance}} prep_processor_queue_size"
    }
   ]
  },
  {
   "title": "prep_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prep_processor_request_queued{}",
     "legendFormat": "{{instance}} prep_processor_request_queued"
    }
   ]
  },
  {
   "title": "outstanding_changes_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "outstanding_changes_queued{}",
     "legendFormat": "{{instance}} outstanding_changes_queued"
    },
    {
     "expr": "outstanding_changes_removed{}",
     "legendFormat": "{{instance}} outstanding_changes_removed"
    }
   ]
  },
  {
   "title": "close_session_prep_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(close_session_prep_time_sum{}[$interval])",
     "legendFormat": "{{instance}} close_session_prep_time"
    }
   ]
  },
  { "title": "Sync_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 } },
  {
   "title": "sync_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_process_time_sum{}[$interval])",
     "legendFormat": "{{instance}} sync_process_time"
    }
   ]
  },
  {
   "title": "sync_processor_queue_flush_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_queue_flush_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} sync_processor_queue_flush_time"
    }
   ]
  },
  {
   "title": "sync_processor_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 207 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_queue_size_sum{}[$interval])",
     "legendFormat": "{{instance}} sync_processor_queue_size"
    }
   ]
  },
  {
   "title": "sync_processor_request_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_processor_request_queued{}",
     "legendFormat": "{{instance}} sync_processor_request_queued"
    }
   ]
  },
  {
   "title": "sync_processor_batch_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_processor_batch_size_sum{}[$interval])",
     "legendFormat": "{{instance}} sync_processor_batch_size"
    }
   ]
  },
  { "title": "Commit_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 } },
  {
   "title": "commit_process_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(commit_process_time_sum{}[$interval])",
     "legendFormat": "{{instance}} commit_process_time"
    },
    {
     "expr": "rate(read_commitproc_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} read_commitproc_time"
    },
    {
     "expr": "rate(write_commitproc_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} write_commitproc_time"
    }
   ]
  },
  {
   "title": "commit_proc_req_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_commit_proc_req_queued_sum{}[$interval])",
     "legendFormat": "{{instance}} write_commit_proc_req_queued"
    },
    {
     "expr": "rate(read_commit_proc_req_queued_sum{}[$interval])",
     "legendFormat": "{{instance}} read_commit_proc_req_queued"
    },
    {
     "expr": "rate(commit_commit_proc_req_queued_sum{}[$interval])",
     "legendFormat": "{{instance}} commit_commit_proc_req_queued"
    }
   ]
  },
  {
   "title": "requests_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 224 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(requests_in_session_queue_sum{}[$interval])",
     "legendFormat": "{{instance}} requests_in_session_queue"
    }
   ]
  },
  {
   "title": "commit_proc_issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_commit_proc_issued_sum{}[$interval])",
     "legendFormat": "{{instance}} read_commit_proc_issued"
    },
    {
     "expr": "rate(write_commit_proc_issued_sum{}[$interval])",
     "legendFormat": "{{instance}} write_commit_proc_issued"
    }
   ]
  },
  {
   "title": "concurrent_request_processing_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(concurrent_request_processing_in_commit_processor_sum{}[$interval])",
     "legendFormat": "{{instance}} concurrent_request_processing_in_commit_processor"
    }
   ]
  },
  {
   "title": "time_waiting_empty_pool_in_commit_processor_read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 232 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(time_waiting_empty_pool_in_commit_processor_read_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} time_waiting_empty_pool_in_commit_processor_read"
    }
   ]
  },
  {
   "title": "pending_session_queue_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 240 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pending_session_queue_size_sum{}[$interval])",
     "legendFormat": "{{instance}} pending_session_queue_size"
    }
   ]
  },
  {
   "title": "local_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 240 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(local_write_committed_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} local_write_committed_time_ms"
    }
   ]
  },
  {
   "title": "server_write_committed_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 240 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(server_write_committed_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} server_write_committed_time"
    }
   ]
  },
  {
   "title": "write_batch_time_in_commit_processor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 248 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_batch_time_in_commit_processor_sum{}[$interval])",
     "legendFormat": "{{instance}} write_batch_time_in_commit_processor"
    }
   ]
  },
  {
   "title": "reads_after_write_in_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 248 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_after_write_in_session_queue_sum{}[$interval])",
     "legendFormat": "{{instance}} reads_after_write_in_session_queue"
    }
   ]
  },
  {
   "title": "session_queues_drained",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 248 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(session_queues_drained_sum{}[$interval])",
     "legendFormat": "{{instance}} session_queues_drained"
    }
   ]
  },
  {
   "title": "reads_issued_from_session_queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(reads_issued_from_session_queue_sum{}[$interval])",
     "legendFormat": "{{instance}} reads_issued_from_session_queue"
    }
   ]
  },
  {
   "title": "request_commit_queued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "request_commit_queued{}",
     "legendFormat": "{{instance}} request_commit_queued"
    }
   ]
  },
  { "title": "Final_Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 264 } },
  {
   "title": "write_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 265 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(write_final_proc_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} write_final_proc_time_ms"
    }
   ]
  },
  {
   "title": "read_final_proc_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 265 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(read_final_proc_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} read_final_proc_time_ms"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 273 } },
  {
   "title": "read_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(readlatency_sum{}[$interval])",
     "legendFormat": "{{instance}} readlatency"
    }
   ]
  },
  {
   "title": "update_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(updatelatency_sum{}[$interval])",
     "legendFormat": "{{instance}} updatelatency"
    }
   ]
  },
  {
   "title": "max_min_avg_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "max_latency{}", "legendFormat": "{{instance}} max_latency" },
    { "expr": "min_latency{}", "legendFormat": "{{instance}} min_latency" },
    { "expr": "avg_latency{}", "legendFormat": "{{instance}} avg_latency" }
   ]
  },
  {
   "title": "proposal_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 282 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proposal_latency_sum{}[$interval])",
     "legendFormat": "{{instance}} proposal_latency"
    }
   ]
  },
  {
   "title": "quorum_ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(quorum_ack_latency_sum{}[$interval])",
     "legendFormat": "{{instance}} quorum_ack_latency"
    }
   ]
  },
  {
   "title": "ack_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 290 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ack_latency_sum{}[$interval])",
     "legendFormat": "{{instance}} ack_latency_sum"
    }
   ]
  },
  {
   "title": "propagation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(propagation_latency_sum{}[$interval])",
     "legendFormat": "{{instance}} propagation_latency"
    }
   ]
  },
  {
   "title": "commit_propagation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(commit_propagation_latency_sum{}[$interval])",
     "legendFormat": "{{instance}} commit_propagation_latency"
    }
   ]
  },
  {
   "title": "proposal_ack_creation_latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "proposal_ack_creation_latency{}",
     "legendFormat": "{{instance}} proposal_ack_creation_latency-{{quantile}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 314 } },
  {
   "title": "tls_handshake",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 315 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tls_handshake_exceeded{}",
     "legendFormat": "{{instance}} tls_handshake_exceeded"
    },
    {
     "expr": "outstanding_tls_handshake{}",
     "legendFormat": "{{instance}} outstanding_tls_handshake"
    }
   ]
  },
  {
   "title": "ensemble_auth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 315 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ensemble_auth_fail{}",
     "legendFormat": "{{instance}} ensemble_auth_fail"
    },
    {
     "expr": "ensemble_auth_success{}",
     "legendFormat": "{{instance}} ensemble_auth_success"
    },
    {
     "expr": "ensemble_auth_skip{}",
     "legendFormat": "{{instance}} ensemble_auth_skip"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 323 } },
  {
   "title": "jvm_classes_loaded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 324 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(jvm_classes_loaded{})" }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 324 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(jvm_threads_current{})" }
   ]
  },
  {
   "title": "jvm_threads_deadlocked",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 324 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(jvm_threads_deadlocked{})" }
   ]
  },
  {
   "title": "jvm_pause_time_ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 332 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_pause_time_ms_sum{}[$interval])",
     "legendFormat": "{{instance}} jvm_pause_time_ms"
    }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 332 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{}[$interval])",
     "legendFormat": "{{instance}} gc:{{gc}}"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 332 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_state{}", "legendFormat": "{{instance}} state:{{state}}" }
   ]
  },
  {
   "title": "jvm_memory_pool_bytes_used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 340 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used{}", "legendFormat": "{{instance}} pool:{{pool}}" }
   ]
  }
 ]
}